vich_uploader:
  db_driver: orm

  mappings:
    products:
      uri_prefix: /images/products
      upload_destination: "%kernel.project_dir%/public/images/products"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    event_pdfs:
      uri_prefix: /uploads/pdfs
      upload_destination: "%kernel.project_dir%/public/uploads/pdfs"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    event_images:
      uri_prefix: /uploads/events
      upload_destination: "%kernel.project_dir%/public/uploads/events"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer